name: ci-cd

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-cd.yaml
      - pyproject.toml
      - Makefile
      - src/**
      - tests/**
  release:
    types:
      - published

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: install-dev-dependencies
        run: uv sync --group dev

      - name: quality
        run: make quality

      - name: types
        run: make types

      - name: tests
        run: make tests

  deploy-docs:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: install-docs
        run: uv sync --group dev --extra docs

      - name: deploy-to-gh-pages
        run: uv run --group dev --extra docs mkdocs gh-deploy --force

  publish-package:
    needs: ci
    if: github.event_name == 'release'

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: setup-uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: build-package
        run: uv build

      - name: publish-package
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
