name: ci-cd

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci-cd.yaml
      - src/**
      - tests/**
  release:
    types:
      - published

jobs:
  check-quality:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: quality
        run: make quality

  check-types:
    needs: check-quality

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: types
        run: make types

  run-tests:
    needs: check-types

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install-package
        run: uv sync --group dev

      - name: tests
        run: make tests

  deploy-docs:
    needs: run-tests

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install-docs
        run: uv sync --group dev --extra docs

      - name: deploy-to-gh-pages
        run: uv run --group dev --extra docs mkdocs gh-deploy --force

  publish-package:
    needs: deploy-docs
    if: github.event_name == 'release'

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build-package
        run: uv build

      - name: publish-package
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
